table Teen_Mental_Health_Dataset
	lineageTag: e91e1e51-5863-4f0c-82b7-9529d323ebf0

	column age
		dataType: int64
		formatString: 0
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: 3cc517ca-e938-4073-af02-003d0efb6b97
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = User

	column gender
		dataType: string
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: 79dbe3c3-9ae7-40c5-b08d-6927f2368c2a
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column daily_social_media_hours
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 39b3fbd1-8d53-4769-96c8-3216556b9969
		summarizeBy: none
		sourceColumn: daily_social_media_hours

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column platform_usage
		dataType: string
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: c094f4ea-1af1-44d2-95f3-e88a0c71b5ac
		summarizeBy: none
		sourceColumn: platform_usage

		annotation SummarizationSetBy = Automatic

	column sleep_hours
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 79a6271c-7d16-4801-b350-a3f4a07eb889
		summarizeBy: none
		sourceColumn: sleep_hours

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column screen_time_before_sleep
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 7ea26e07-92a6-41bc-8a84-7736def41705
		summarizeBy: none
		sourceColumn: screen_time_before_sleep

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column academic_performance
		dataType: double
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: b4568960-5734-4964-af88-f9bad11a6b58
		summarizeBy: none
		sourceColumn: academic_performance

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column physical_activity
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 708542fb-143d-4525-b02c-38b648933f95
		summarizeBy: none
		sourceColumn: physical_activity

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column social_interaction_level
		dataType: string
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: 030ccd0c-7833-4fc0-9158-fb67b32ddf6a
		summarizeBy: none
		sourceColumn: social_interaction_level

		annotation SummarizationSetBy = Automatic

	column stress_level
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: 29986051-b067-4703-adb8-98c3c29a189f
		summarizeBy: none
		sourceColumn: stress_level

		annotation SummarizationSetBy = User

	column anxiety_level
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: d3f90198-1e9c-406c-80bf-b47a7e83add1
		summarizeBy: none
		sourceColumn: anxiety_level

		annotation SummarizationSetBy = User

	column addiction_level
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: 4ddf60cc-45a9-48a2-b31f-26b2780b0290
		summarizeBy: none
		sourceColumn: addiction_level

		annotation SummarizationSetBy = User

	column depression_label
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: 33883042-7e67-4884-a694-35daa5d34ee3
		summarizeBy: none
		sourceColumn: depression_label

		annotation SummarizationSetBy = User

	column total_distress
		dataType: int64
		formatString: 0
		lineageTag: 63462c8d-4b46-4e39-9230-16b7a7f93c53
		summarizeBy: sum
		sourceColumn: total_distress

		annotation SummarizationSetBy = Automatic

	partition Teen_Mental_Health_Dataset = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\rohit\OneDrive\PowerBI\Teenage mental health\Teen_Mental_Health_Dataset.csv"), [Delimiter = ",", Columns = 13, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"age", Int64.Type}, {"gender", type text}, {"daily_social_media_hours", type number}, {"platform_usage", type text}, {"sleep_hours", type number}, {"screen_time_before_sleep", type number}, {"academic_performance", type number}, {"physical_activity", type number}, {"social_interaction_level", type text}, {"stress_level", Int64.Type}, {"anxiety_level", Int64.Type}, {"addiction_level", Int64.Type}, {"depression_label", Int64.Type}}, "en-US"),
				    #"Added total_distress" = Table.AddColumn(#"Changed column type", "total_distress", each [stress_level] + [anxiety_level] + [addiction_level], Int64.Type)
				in
				  #"Added total_distress"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

