table Teen_Mental_Health_Dataset
	lineageTag: e91e1e51-5863-4f0c-82b7-9529d323ebf0

	column age
		dataType: int64
		formatString: 0
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: 3cc517ca-e938-4073-af02-003d0efb6b97
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = User

	column gender
		dataType: string
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: 79dbe3c3-9ae7-40c5-b08d-6927f2368c2a
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column daily_social_media_hours
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 39b3fbd1-8d53-4769-96c8-3216556b9969
		summarizeBy: none
		sourceColumn: daily_social_media_hours

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column platform_usage
		dataType: string
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: c094f4ea-1af1-44d2-95f3-e88a0c71b5ac
		summarizeBy: none
		sourceColumn: platform_usage

		annotation SummarizationSetBy = Automatic

	column sleep_hours
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 79a6271c-7d16-4801-b350-a3f4a07eb889
		summarizeBy: none
		sourceColumn: sleep_hours

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column screen_time_before_sleep
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 7ea26e07-92a6-41bc-8a84-7736def41705
		summarizeBy: none
		sourceColumn: screen_time_before_sleep

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column academic_performance
		dataType: double
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: b4568960-5734-4964-af88-f9bad11a6b58
		summarizeBy: none
		sourceColumn: academic_performance

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column physical_activity
		dataType: double
		displayFolder: Behavioral & Lifestyle Factors (Independent Variables)
		lineageTag: 708542fb-143d-4525-b02c-38b648933f95
		summarizeBy: none
		sourceColumn: physical_activity

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column social_interaction_level
		dataType: string
		displayFolder: Dimensions (Identifiers & Categoricals)
		lineageTag: 030ccd0c-7833-4fc0-9158-fb67b32ddf6a
		summarizeBy: none
		sourceColumn: social_interaction_level

		annotation SummarizationSetBy = Automatic

	column stress_level
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: 29986051-b067-4703-adb8-98c3c29a189f
		summarizeBy: none
		sourceColumn: stress_level

		annotation SummarizationSetBy = User

	column anxiety_level
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: d3f90198-1e9c-406c-80bf-b47a7e83add1
		summarizeBy: none
		sourceColumn: anxiety_level

		annotation SummarizationSetBy = User

	column addiction_level
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: 4ddf60cc-45a9-48a2-b31f-26b2780b0290
		summarizeBy: none
		sourceColumn: addiction_level

		annotation SummarizationSetBy = User

	column depression_label
		dataType: int64
		formatString: 0
		displayFolder: Key Metrics (Outcome Scores)
		lineageTag: 33883042-7e67-4884-a694-35daa5d34ee3
		summarizeBy: none
		sourceColumn: depression_label

		annotation SummarizationSetBy = User

	column total_distress
		dataType: int64
		formatString: 0
		lineageTag: 63462c8d-4b46-4e39-9230-16b7a7f93c53
		displayFolder: Derived Insights
		summarizeBy: sum
		sourceColumn: total_distress

		annotation SummarizationSetBy = Automatic

	column Total_Distress_Risk
		dataType: string
		lineageTag: 0d8166b5-ed1c-468c-ba19-47224fa94463
		summarizeBy: none
		sourceColumn: Total_Distress_Risk
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column Anxiety_Risk
		dataType: string
		lineageTag: ba155c32-580d-4f7a-8c11-a6a5be036688
		summarizeBy: none
		sourceColumn: Anxiety_Risk
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column Addiction_Risk
		dataType: string
		lineageTag: 43a8bbf3-c811-40e6-8a8e-33e74752cf55
		summarizeBy: none
		sourceColumn: Addiction_Risk
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column Stress_Risk
		dataType: string
		lineageTag: 34a26489-54dd-46e9-86a4-92a2c9c01bec
		summarizeBy: none
		sourceColumn: Stress_Risk
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column Academic_Status
		dataType: string
		lineageTag: c43d58ff-575f-4749-923d-3532a0c51973
		summarizeBy: none
		sourceColumn: Academic_Status
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column SocialMedia_Risk
		dataType: string
		lineageTag: 3e99cfc9-2461-4856-bafa-d15f0a1c41d0
		summarizeBy: none
		sourceColumn: SocialMedia_Risk
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column SleepPrep_Risk
		dataType: string
		lineageTag: a7cbf3f6-4504-4d1f-958d-9ae4e3cd8821
		summarizeBy: none
		sourceColumn: SleepPrep_Risk
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column Sleep_Quality
		dataType: string
		lineageTag: 311cec87-1ba3-4ed4-ab59-96111b745738
		summarizeBy: none
		sourceColumn: Sleep_Quality
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column Activity_Level
		dataType: string
		lineageTag: 6dadad18-6b99-40c7-8840-50c75f2dd7e3
		summarizeBy: none
		sourceColumn: Activity_Level
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	column Depression_Status
		dataType: string
		lineageTag: 5efbe085-aa65-4004-a9ac-ffbfb03d7bf2
		summarizeBy: none
		sourceColumn: Depression_Status
		displayFolder: Derived Insights

		annotation SummarizationSetBy = Automatic

	partition Teen_Mental_Health_Dataset = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\rohit\OneDrive\PowerBI\Teenage mental health\Teen_Mental_Health_Dataset.csv"), [Delimiter = ",", Columns = 13, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"age", Int64.Type}, {"gender", type text}, {"daily_social_media_hours", type number}, {"platform_usage", type text}, {"sleep_hours", type number}, {"screen_time_before_sleep", type number}, {"academic_performance", type number}, {"physical_activity", type number}, {"social_interaction_level", type text}, {"stress_level", Int64.Type}, {"anxiety_level", Int64.Type}, {"addiction_level", Int64.Type}, {"depression_label", Int64.Type}}, "en-US"),
				    #"Added total_distress" = Table.AddColumn(#"Changed column type", "total_distress", each [stress_level] + [anxiety_level] + [addiction_level], Int64.Type),
				
				
				  #"Added Total Distress Risk" = Table.AddColumn(#"Added total_distress", "Total_Distress_Risk", each if [total_distress] > 16 then "Very High Risk" else
				    if [total_distress] > 12 then "Medium Risk" else
				    if [total_distress] > 9 then "Low Risk" else "Unclassified", type text),
				
				    #"Added Anxiety Risk" = Table.AddColumn(#"Added Total Distress Risk", "Anxiety_Risk", each if [anxiety_level] > 7 then "High Risk"
				        else if [anxiety_level] > 4 then "Medium Risk" else "Low Risk", type text),
				
				    #"Added Addiction Risk" = Table.AddColumn(#"Added Anxiety Risk", "Addiction_Risk", each if [addiction_level] > 6 then "High Risk"
				        else if [addiction_level] > 3 then "Medium Risk" else "Low Risk", type text),
				
				    #"Added Stress Risk" = Table.AddColumn(#"Added Addiction Risk", "Stress_Risk", each if [stress_level] > 7 then "High Risk"
				        else if [stress_level] > 4 then "Medium Risk" else "Low Risk", type text),
				
				    #"Added Academic Status" = Table.AddColumn(#"Added Stress Risk", "Academic_Status", each if [academic_performance] >= 3.5 then "High Performing"
				        else if [academic_performance] >= 2.5 then "At Risk/Medium Performance" else "Needs Support", type text),
				
				    #"Added Social Media Risk" = Table.AddColumn(#"Added Academic Status", "SocialMedia_Risk", each if [daily_social_media_hours] > 5 then "High Risk (Excessive Usage)"
				        else if [daily_social_media_hours] > 2 then "Medium Risk (Moderate/Cautionary Usage)" else "Low Risk (Healthy Usage)", type text),
				
				    #"Added Sleep Prep Risk" = Table.AddColumn(#"Added Social Media Risk", "SleepPrep_Risk", each if [screen_time_before_sleep] > 2 then "High Risk (Significant Disruption)"
				        else if [screen_time_before_sleep] > 1 then "Medium Risk (Caution Advised)" else "Low Risk", type text),
				
				    #"Added Sleep Quality" = Table.AddColumn(#"Added Sleep Prep Risk", "Sleep_Quality", each if [sleep_hours] > 8 then "Optimal"
				        else if [sleep_hours] >= 6 then "Acceptable" else "Poor", type text),
				
				    #"Added Activity Level" = Table.AddColumn(#"Added Sleep Quality", "Activity_Level", each if [physical_activity] = 2 then "High Activity"
				        else if [physical_activity] = 1 then "Medium Activity" else "Low Activity", type text),
				
				    #"Added Depression Status" = Table.AddColumn(#"Added Activity Level", "Depression_Status", each if [depression_label] = 1 then "Present" else "Absent", type text)
				
				in #"Added Depression Status"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

